interface Food {
	value: string
	label: string
	disabled: boolean
}
interface Category {
	label: string
	options: Food[]
}

export const ALL_OPTIONS: Category[] = [
	{
		label: "Animal Shapes",
		options: [
			{ value: "Dog", label: "i-fluent:animal-dog-24-filled", disabled: false },
			{ value: "Fish", label: "i-icon-park-outline:fish-one", disabled: false },
			{ value: "Dolphin", label: "i-icon-park-outline:dolphin", disabled: false },
			{ value: "Cat", label: "i-fluent:animal-cat-16-filled", disabled: false },
			{ value: "Horse", label: "i-mdi:horse-variant-fast", disabled: false },
			{ value: "Bird", label: "i-mingcute:bird-line", disabled: false },
			{ value: "Spider", label: "i-mdi:spider", disabled: false }
		]
	},
	{
		label: "Stuff & Things",
		options: [
			{ value: "Guitar", label: "i-mingcute:guitar-line", disabled: false },
			{ value: "Typhoon", label: "i-mingcute:typhoon-line", disabled: false },
			{ value: "Traffic Lights", label: "i-mingcute:traffic-lights-line", disabled: false },
			{ value: "Trophy Base", label: "i-ep:trophy-base", disabled: false },
			{ value: "Toy Horse", label: "i-mingcute:toy-horse-line", disabled: false },
			{ value: "Train", label: "i-mingcute:train-line", disabled: false },
			{ value: "Tree", label: "i-mingcute:tree-line", disabled: false },
			{ value: "Tree 4", label: "i-mingcute:tree-4-line", disabled: false },
			{ value: "UFO 2", label: "i-mingcute:ufo-2-line", disabled: false },
			{ value: "Video", label: "i-mingcute:video-line", disabled: false },
			{ value: "World 2", label: "i-mingcute:world-2-line", disabled: false },
			{ value: "Windows", label: "i-mingcute:windows-line", disabled: false },
			{ value: "Watch 2", label: "i-mingcute:watch-2-line", disabled: false },
			{ value: "Thunderstorm", label: "i-mingcute:thunderstorm-line", disabled: false },
			{ value: "Sweats", label: "i-mingcute:sweats-line", disabled: false },
			{ value: "Sun Fog", label: "i-mingcute:sun-fog-line", disabled: false },
			{ value: "Sun Cloudy", label: "i-mingcute:sun-cloudy-line", disabled: false },
			{ value: "Sparkles 2", label: "i-mingcute:sparkles-2-line", disabled: false },
			{ value: "Shopping Cart 2", label: "i-mingcute:shopping-cart-2-line", disabled: false },
			{ value: "Shirt", label: "i-mingcute:shirt-line", disabled: false },
			{ value: "Receive Money", label: "i-mingcute:receive-money-line", disabled: false },
			{ value: "Bill", label: "i-mingcute:bill-line", disabled: false },
			{ value: "Bike", label: "i-mingcute:bike-line", disabled: false },
			{ value: "Carrot", label: "i-mingcute:carrot-line", disabled: false },
			{ value: "Check 2", label: "i-mingcute:check-2-line", disabled: false },
			{ value: "Chess", label: "i-mingcute:chess-line", disabled: false },
			{ value: "Audio Tape", label: "i-mingcute:audio-tape-line", disabled: false },
			{ value: "Airdrop", label: "i-mingcute:airdrop-line", disabled: false },
			{ value: "Plant", label: "i-material-symbols-light:potted-plant-rounded", disabled: false },
			{ value: "Restaurant", label: "i-ic:outline-restaurant-menu", disabled: false },
			{ value: "Book", label: "i-mdi:book-open-page-variant-outline", disabled: false },
			{ value: "Wrench", label: "i-oui:wrench", disabled: false },
			{ value: "Fire", label: "i-nimbus:fire", disabled: false },
			{ value: "Phone", label: "i-heroicons:phone-16-solid", disabled: false },
			{ value: "Bell Ringing", label: "i-tabler:bell-ringing", disabled: false },
			{ value: "Baby Carriage	", label: "i-tabler:baby-carriage", disabled: false },
			{ value: "Broadcast", label: "i-icon-park-outline:broadcast", disabled: false },
			{ value: "Cardioelectric", label: "i-icon-park-outline:cardioelectric", disabled: false },
			{ value: "Airplane", label: "i-icon-park-outline:airplane", disabled: false },
			{ value: "Backhoe", label: "i-tabler:backhoe", disabled: false },
			{ value: "Leaves Two", label: "i-icon-park-outline:leaves-two", disabled: false },
			{ value: "Trophy", label: "i-mage:trophy", disabled: false },
			{ value: "Hare Fill", label: "i-f7:hare-fill", disabled: false },
			{ value: "Suit Heart Fill", label: "i-f7:suit-heart-fill", disabled: false },
			{ value: "Cactus", label: "i-tabler:cactus", disabled: false },
			{ value: "Anchor", label: "i-tabler:anchor", disabled: false },
			{ value: "Armchair", label: "i-tabler:armchair", disabled: false },
			{ value: "Atom", label: "i-tabler:atom", disabled: false },
			{ value: "Bandage", label: "i-tabler:bandage", disabled: false },
			{ value: "Balloon", label: "i-tabler:balloon", disabled: false },
			{ value: "Headset", label: "i-ep:headset", disabled: false },
			{ value: "Sugar", label: "i-ep:sugar", disabled: false },
			{ value: "Milk Tea", label: "i-ep:milk-tea", disabled: false },
			{ value: "Coffee Cup", label: "i-ep:coffee-cup", disabled: false },
			{ value: "Cellphone", label: "i-ep:cellphone", disabled: false },
			{ value: "Cpu", label: "i-ep:cpu", disabled: false },
			{ value: "Quartz Watch", label: "i-ep:quartz-watch", disabled: false },
			{ value: "Sunrise", label: "i-ep:sunrise", disabled: false },
			{ value: "Umbrella", label: "i-ep:umbrella", disabled: false },
			{ value: "Trophy Base", label: "i-ep:trophy-base", disabled: false }
		]
	},
	{
		label: "Shapes & Symbols",
		options: [
			{ value: "Lightning", label: "i-mingcute:lightning-line", disabled: false },
			{ value: "Align Box", label: "i-tabler:align-box-bottom-center", disabled: false },
			{ value: "Magic 2", label: "i-mingcute:magic-2-line", disabled: false },
			{ value: "Classify", label: "i-mingcute:classify-line", disabled: false },
			{ value: "Help", label: "i-ep:help", disabled: false },
			{ value: "Microphone", label: "i-mdi:microphone-variant", disabled: false },
			{ value: "Navigation", label: "i-mdi:navigation-variant-outline", disabled: false },
			{ value: "Star", label: "i-oui:star-filled", disabled: false },
			{ value: "Left Small Up", label: "i-icon-park-outline:left-small-up", disabled: false },
			{ value: "Cloud", label: "i-tabler:cloud", disabled: false },
			{ value: "Group", label: "i-mingcute:group-line", disabled: false },
			{ value: "Cloud Upload", label: "i-tabler:cloud-upload", disabled: false },
			{ value: "Circle Check", label: "i-ep:circle-check", disabled: false },
			{ value: "Circle Check Filled", label: "i-ep:circle-check-filled", disabled: false },
			{ value: "Arrow Left", label: "i-tabler:arrow-big-left-filled", disabled: false },
			{ value: "Arrow Down", label: "i-tabler:arrow-big-down-lines-filled", disabled: false },
			{ value: "Arrow Up", label: "i-tabler:arrow-big-up-filled", disabled: false },
			{ value: "Arrow Right", label: "i-tabler:arrow-big-right-filled", disabled: false },
			{ value: "Arrow Badge Left", label: "i-tabler:arrow-badge-left", disabled: false },
			{ value: "Arrow Badge Right", label: "i-tabler:arrow-badge-right", disabled: false },
			{ value: "Arrow Badge Up", label: "i-tabler:arrow-badge-up", disabled: false },
			{ value: "Arrow Badge Down", label: "i-tabler:arrow-badge-down", disabled: false },
			{ value: "Document Add", label: "i-ep:document-add", disabled: false },
			{ value: "Data Line", label: "i-ep:data-line", disabled: false },
			{ value: "Opportunity", label: "i-ep:opportunity", disabled: false },
			{ value: "Dollar", label: "i-heroicons:currency-dollar-solid", disabled: false },
			{ value: "Lock", label: "i-heroicons:lock-closed-solid", disabled: false },
			{ value: "Lock Open", label: "i-heroicons:lock-open-20-solid", disabled: false },
			{ value: "Thumb Up", label: "i-heroicons:hand-thumb-up-20-solid", disabled: false },
			{ value: "Thumb Down", label: "i-heroicons:hand-thumb-down-solid", disabled: false }
		]
	},
	{
		label: "AI and Faces",
		options: [
			{ value: "Pouting Face", label: "i-icon-park-outline:pouting-face", disabled: false },
			{ value: "Robot Happy", label: "i-mage:robot-happy", disabled: false },
			{ value: "Mood Crazy Happy", label: "i-tabler:mood-crazy-happy", disabled: false },
			{ value: "Mood Happy", label: "i-tabler:mood-happy", disabled: false },
			{ value: "Ghost", label: "i-mingcute:ghost-line", disabled: false },
			{ value: "Tongue", label: "i-mingcute:tongue-line", disabled: false },
			{ value: "Skull", label: "i-mingcute:skull-line", disabled: false },
			{ value: "AI 1", label: "i-ri:robot-2-line", disabled: false },
			{ value: "AI 2", label: "i-ant-design:robot-outlined", disabled: false },
			{ value: "AI 3", label: "i-bi:robot", disabled: false },
			{ value: "AI 4", label: "i-icon-park-outline:robot", disabled: false },
			{ value: "AI 5", label: "i-hugeicons:machine-robot", disabled: false },
			{ value: "AI 6", label: "i-teenyicons:robot-outline", disabled: false }
		]
	},
	{
		label: "Brands & Logos",
		options: [
			{ value: "OpenAI", label: "i-mingcute:openai-line", disabled: false },
			{ value: "Github", label: "i-mingcute:github-line", disabled: false },
			{ value: "Google", label: "i-mingcute:google-line", disabled: false },
			{ value: "Chrome Filled", label: "i-ep:chrome-filled", disabled: false },
			{ value: "Apple", label: "i-mingcute:apple-line", disabled: false },
			{ value: "Whatsapp", label: "i-mingcute:whatsapp-line", disabled: false },
			{ value: "Logo Instagram", label: "i-f7:logo-instagram", disabled: false },
			{ value: "Logo Apple", label: "i-f7:logo-apple", disabled: false },
			{ value: "Logo Android", label: "i-f7:logo-android", disabled: false },
			{ value: "Logo Windows", label: "i-f7:logo-windows", disabled: false },
			{ value: "PHP", label: "i-tabler:brand-php", disabled: false },
			{ value: "Spotify", label: "i-mingcute:spotify-line", disabled: false },
			{ value: "Shopee", label: "i-tabler:brand-shopee", disabled: false },
			{ value: "Wix", label: "i-tabler:brand-wix", disabled: false },
			{ value: "Facebook", label: "i-f7:logo-facebook", disabled: false },
			{ value: "Twitter", label: "i-f7:logo-twitter", disabled: false },
			{ value: "X", label: "i-tabler:brand-x", disabled: false },
			{ value: "Tiktok", label: "i-tabler:brand-tiktok", disabled: false },
			{ value: "Reddit", label: "i-tabler:brand-reddit", disabled: false },
			{ value: "Npm", label: "i-tabler:brand-npm", disabled: false },
			{ value: "Netflix", label: "i-tabler:brand-netflix", disabled: false },
			{ value: "Paypal", label: "i-tabler:brand-paypal", disabled: false },
			{ value: "Stripe", label: "i-tabler:brand-stripe", disabled: false },
			{ value: "Docker", label: "i-tabler:brand-docker", disabled: false },
			{ value: "Flutter", label: "i-tabler:brand-flutter", disabled: false },
			{ value: "Discord", label: "i-tabler:brand-discord", disabled: false },
			{ value: "Laravel", label: "i-tabler:brand-laravel", disabled: false },
			{ value: "Solidjs", label: "i-tabler:brand-solidjs", disabled: false },
			{ value: "Svelte", label: "i-tabler:brand-svelte", disabled: false },
			{ value: "Supabase", label: "i-tabler:brand-supabase", disabled: false },
			{ value: "Cashapp", label: "i-tabler:brand-cashapp", disabled: false },
			{ value: "React", label: "i-tabler:brand-react", disabled: false },
			{ value: "Vite", label: "i-tabler:brand-vite", disabled: false },
			{ value: "Vscode", label: "i-tabler:brand-vscode", disabled: false },
			{ value: "Typescript", label: "i-tabler:brand-typescript", disabled: false }
		]
	}
]
